from __future__ import annotations

from typing import Protocol

from .domain import CompanyProfile, Evidence, LeadResult, WorkflowRunLog


class CompanyRepository(Protocol):
    def upsert_company(self, company: CompanyProfile) -> None: ...
    def get_company(self, siren: str) -> CompanyProfile | None: ...


class EvidenceRepository(Protocol):
    def add_evidence(self, evidence: Evidence) -> None: ...
    def list_evidence(self, siren: str) -> list[Evidence]: ...


class LeadResultRepository(Protocol):
    def add_result(self, workflow_run_id: str, result: LeadResult) -> None: ...
    def list_results(self, workflow_run_id: str) -> list[LeadResult]: ...


class WorkflowRunRepository(Protocol):
    def start_run(self, workflow_name: str) -> str: ...
    def add_log(self, workflow_run_id: str, log: WorkflowRunLog) -> None: ...
    def finish_run(self, workflow_run_id: str, status: str) -> None: ...
